version: '3.9'

services:

  lyricfa:
    image: lyricfa_service
    container_name: lyricfa
    build:
      args:
        user: ${MAIN_SERVICE_USER}
        uid: ${MAIN_SERVICE_ID}
      dockerfile: DockerFile
    volumes:
      - lyricfa-service:/var/www/lyricfa-service/
    restart: always

volumes:
  lyricfa-service:
