FROM php:8.2.3-fpm

ARG user
ARG uid

VOLUME app-service /var/www/app-service/

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

COPY ./src /var/www/app-service/
# COPY ./src/.env.example /var/www/app-service/.env

RUN chmod 777 -R /var/www/app-service/storage/ && \
    chown -R www-data:www-data /var/www/app-service

ENV COMPOSER_ALLOW_SUPERUSER=1

WORKDIR /var/www/app-service

RUN composer install --prefer-dist --no-interaction && \
    php artisan optimize:clear && \
    php artisan config:cache && \
    php artisan route:cache

USER $user

ENTRYPOINT php artisan serve --port=8000 --host=0.0.0.0

EXPOSE 8000